### ISSUE TITLE
Samme MUI theme som Fondet

### ISSUE THREAD

**Issue by martcl** [TIHLDE/jubileum#16]
Bruk samme theme som fondet/tihlde.org

**Comment by MindChirp** [comment]
Innebærer det å bruke samme layout? Isåfall antar jeg at gradienten fjernes, og at undersidene for eksempelvis "Tihlde Daljer" får et lignende layout som dette: 
![image](https://user-images.githubusercontent.com/33499052/214295590-c01ee864-ec41-42b2-a6fb-b21d9d0c8722.png)

Jeg kan fikse nedtelleren og forsida relativt enkelt (fjerne gradienten, og bruke samme fargepallett som fondet sin side), hvis det er ønskelig 👌
