### ISSUE TITLE
Innholdet i footeren er ikke midtstilt i flexboxen

### ISSUE THREAD

**Issue by MindChirp** [TIHLDE/jubileum#57]
Innholdet er ikke midtstilt, og det ser ikke helt bra ut. Wrapperen som innholdet er i, er heller ikke ordentlig midtstilt
![image](https://user-images.githubusercontent.com/33499052/218866306-11eaa8f9-6f85-45e3-8bff-5fe7ec6b5980.png)

**Comment by eriskjel** [comment]
ikke tenk
